### ISSUE TITLE
#unitarianChurch vs. #unitarianMovement

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#1]
We currently have both the #unitarianChurch and #unitarianMovement urn's in the ontology. Which one is the "real" one and what will be the official english label?

**Comment by SusanBrown** [comment]
We have people whose denomination was Unitarian, i.e. they belonged to an organized religious entity.

The question is whether we want Unitarianism to cover this and the more general Unitarian Movement. As I see it, this would be a term parallel to Christianity. (Unitarianism is related to but not (now) strictly a branch of Christianity.) There are certainly uses of "Unitarian" within our dataset that would work better with a reference to the general movement rather than denomination

I'd suggest we have "Unitarianism", by analogy with other terms already in the ontology.
Getty URI: 
http://vocab.getty.edu/aat/300263305
Getty defintion: 
The liberal Protestant movement that arose in Europe during the 16th century Reformation, was embodied in a church in Transylvania, and achieved denominational status in the 19th century in the United Kingdom, the United States, and Canada. It is characterized by a denial of the orthodox Christian doctrines of the Trinity and the divinity of Jesus, the free use of reason in religion, and the belief that God exists in one person. In 1961, in the United States and Canada, it merged with the Universalist denomination to form "Unitarian Universalism." Use also generally for the theological doctrines of the unified nature of God and the humanity of Jesus, first expressed in second- and third-century monarchism and in the teachings of Arius in the third and fourth centuries, and later in the radical Neoplatonist thinkers of the Reformation such as Michael Servetus, Faustus Socinus, and Ferenc David.

Getty calls this a denomination which isn't strictly correct.

Probably the best thing would be to have:
Unitarianism (analogous to Christianity)
Unitarian Church (denomination, like Catholic or Anglican Church and with same relation to Unitarianism as they have to Christianity)
Definition (ours): A denomination of Unitarianism.

This leaves open the ability to fold in Unitarian Universalism etc down the line if needed.

**Comment by SusanBrown** [comment]
Unless this is too elaborate. I'm having second thoughts.

I see that we frequently conflate religions movements/theologies/denominations, as does Getty. So perhaps it is best to go simply with Unitarianism, Quakerism, etc. without getting into the churches. There will be lots of cases where we can't determine from our data which is meant, so the ambiguity will be in our favour in such cases. 

We could still hang on to the major Christian sects as they tended to justify (!) their organizational independence theologically anyway, so they are also "isms".

@rwarren2 what do you think?

**Comment by rwarren2** [comment]
Ok, in this case, I will pull in the #unitarianism from Getty as a term to be consistent with other Religions within the ontologies.

Both #unitarianChurch vs. #unitarianMovement are in use in the tagging right now. I will keep #unitarianChurch, since this is an Organization and thus likely useful as an actor within the context of some entries later and make #unitarianMovement as alternate label of  #unitarianism?

**Comment by susanirenebrown** [comment]
yes

**Comment by rwarren2** [comment]
Reopening this issue. Is "unitarianChurch" used as an organization in Orlando Tagging or as a denomination?

**Comment by SusanBrown** [comment]
It has almost certainly (can't check) been tagged as both an org and a religious denomination in Orlando.

I thought we'd agreed that denominations would most often also be orgs? As opposed to movements which are more amorphous?

Sent from my iPhone

On Jan 23, 2017, at 3:25 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #1<https://github.com/cwrc/ontology/issues/1>.

-

**Comment by alliyya** [comment]
Both have been deprecated in favor of unitarianism
