### ISSUE TITLE
How should geonames show in ontology

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#122]
when replacing the place names (human readable) with the geoname id how does one expect to see it in HuViz?

ex. if a user to query HuViz for all the authors linked to Portugal, but Portugal is not a node in Huviz?

**Comment by SusanBrown** [comment]
From talking this over with Kim ( who was replacing our previous temporary use of placenames for nodes with geonames references, at the request of @rwarren2 ) it seems that there may be several problems here:
1) the revised nodes do not seem to be appearing at all in HuViz
2) the format of the place node -- abbreviated form of the geonames (e.g. geonames:2264397) may be causing problems
3) HuViz doesn't know how to get label info from geonames, since it's not in our data

**Comment by rwarren2** [comment]
Locations have been 'hacks' in our examples since the beginning. The above is correct, labeling of foreign resources in Huviz is still something we need to do.

@smurp has his own priority list to worry about. The simple solution is just to cut and paste the geonames:2264397 labels or node into the example data file which will work with Huviz as-is.

Is the above ok with everyone?

**Comment by SusanBrown** [comment]
Sorry, my query on #77 should instead have gone here:

Please give us an example of how to "cut and paste the geonames:2264397 labels or node into the example data file"

thanks!

**Comment by rwarren2** [comment]
Add: (for portugal)

<http://sws.geonames.org/2643744/>
    a <http://www.geonames.org/ontology#Feature> ;
    rdfs:label "Portugal"@en .

**Comment by susanirenebrown** [comment]
Thanks!

So just to confirm my understanding, we are creating a local version of the geoname entity within our dataset until we can handle external entities better?

**Comment by rwarren2** [comment]
We are just creating the rdfs:label for it. It's the quickest solution that works for everyone.

**Comment by SusanBrown** [comment]
Related to HuViz.

**Comment by JasmineDW** [comment]
From CWRC Onto FAQs:
"placenames need to be linked to geonames -- geonames.org -- (follow Rob’s example of ‘Portugal’ → you replace the instance ‘Portugal’ with a prefix pulled from geonames.org (at the end of the corresponding url)). See Sophia King for example of geoname."

Is this process complete? Does work still need to be done to support it?

**Comment by alliyya** [comment]
I'd consider this process complete or at least an issue that should be flagged in https://gitlab.com/calincs/access/HuViz, 
Seems resolved/in progress from: 
- https://gitlab.com/calincs/access/HuViz/-/issues/351
- https://gitlab.com/calincs/access/HuViz/-/issues/180

Closing as an outdated and irrelevant issue to this project
