### ISSUE TITLE
Deprecate #genderManMale #genderWomanFemale #genderTransMan #genderTransWoman in favour of  #man #woman #transMan #transWoman

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#124]
Also deprecating maleLabel and femaleLabel with no equivalent

also

>   <owl:Class rdf:ID="GenderQueer">
    <rdfs:label xml:lang="en">GenderQueer</rdfs:label>
    <rdfs:label xml:lang="fr">Non-binaire</rdfs:label>
    <skos:note>Listed as non-binary? in french</skos:note>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
    <void:inDataset rdf:resource="#datasetdefinition"/>
  </owl:Class>
  <owl:Class rdf:ID="Androgynous">
    <rdfs:label xml:lang="en">Androgynous</rdfs:label>
    <rdfs:label xml:lang="fr">Androgyne</rdfs:label>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
    <void:inDataset rdf:resource="#datasetdefinition"/>
  </owl:Class>

Should not be classes and instead instances of gender

**Comment by alliyya** [comment]
#111 Should also be discussion

**Comment by rwarren2** [comment]
Consult with Connie about gender and relationships between genre and sexuality.

**Comment by SusanBrown** [comment]
Connie offered this as something to consider:

Here’s a citation to the book that offered the four axes for thinking through gender, sexuality and bodies: sex (female to male continuum), gender role (masculine to feminine continuum), gender identity (man to woman continuum), and sexual orientation (homosexual to heterosexual continuum). In working with continua it offers flexibility, but is still a model that imagines binaries. As helpful as it was in clarifying my own thinking in the 2000s, take it with salt since it predates the emergence of gender non-binary identities (some of which work with continua, and some which don't).

Lev, Arlene Istar. Transgender Emergence: Therapeutic Guidelines for Working with Gender-Variant People and their Families. New York: Routledge, 2004. Print. page 97
