### ISSUE TITLE
Using skos:editorialNote, skos:historyNote, and skos:changeNote to record changes within the ontology

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#184]
@joelacummings would like to propose introducing using skos:editorialNote, skos:historyNote, and skos:changeNote to migrate the recordInfo seen within the MODS extraction. It seems worth tracking how records change and I believe using these concepts would make for a reasonable translation. This would need to be introduced into the CWRC ontology first.

```xml
 <recordInfo>
      <recordContentSource>Orlando, Cambridge University Press</recordContentSource>
      <recordCreationDate encoding="w3cdtf">2016-12-21</recordCreationDate>
      <recordChangeDate encoding="w3cdtf">2016-12-21</recordChangeDate>
      <recordIdentifier source="The Orlando Project">laurma-b.xml</recordIdentifier>
      <recordOrigin>MODS record has been created from an SGML record using an XSLT stylesheet.</recordOrigin>
      <languageOfCataloging>
         <languageTerm type="code" authority="iso639-2b">eng</languageTerm>
         <languageTerm type="text">English</languageTerm>
      </languageOfCataloging>
   </recordInfo>
```

**Comment by joelacummings** [comment]
Decision on this is to create a HistoryNote Concept as skos only supports notes as properties and since we want to tie in Dates along with authors (CWRC Person?) to these notes optionally with a record of what was changed. The concept will use skos properties where applicable.

**Comment by rwarren2** [comment]
The rigidity of skos is sometimes a pain. However, since we are in OWL space and haven't imported skos, it's only an annotation property by default. The range and domain aren't set until we do. We could simply highjack the uri and redefine it: smart parsers will interpret the whole thing as a new term within an empty ontology container and dumb parsers won't notice.

See also muninn/ontology-tools#13 and #48. 

@alliyya and I were thinking of using the old [changeset vocabulary](http://vocab.org/changeset/) coupled with the along with [SIOC](https://www.w3.org/2008/09/msnws/papers/sioc.html) to pull in all of the github tickets and the discussion attached to them. This would neatly link each vocabulary term to it's creation, modification and deletion (deprecation) and link each term to the people who worked on it and the underlying design decisions that led us to perdition.

To make the entire thing look good we could force cs:SubjectOfChange  (et al.) to be a sub-property of skos: HistoryNote.

**Comment by joelacummings** [comment]
Integrating the changes vocabulary seems reasonable that structure is roughly what I had in mind. I don't like the idea of forcing things to be under skos, it confuses people who are used to skos and they put those restrictions in for a reason. I try to use vocabulary where it makes sense but I don't like to force things.

**Comment by rwarren2** [comment]
Actually, quoting from the [skos reference](https://www.w3.org/TR/skos-reference/#notes):

> Note that no range is stated for the SKOS documentation properties, and thus the range of these properties is effectively the class of all resources (rdfs:Resource). 

We can likely implement the above without 'doing violence to other people's vocabularies'.

**Comment by joelacummings** [comment]
Yeah if we treat it as OWL Full we can do that I suppose (We've never made a decision on that). The only downside to OWL Full is that reasoners do not play well.

**Comment by joelacummings** [comment]
Ok so I'm going with the skos:note type as the range and I am creating the ChangeNote class which I will impose some restrictions so we capture the correct data. I will use the Time ontology for capturing date/time in Gregorian format. One can then use the corresponding skos:note type to link to the ChangeNote instance. Also autocorrect hates skos and keeps making it SOS, maybe it's trying to tell me something...

**Comment by joelacummings** [comment]
Regarding GItHub Integration I'd like to link our github accounts to users within the ontology so that you would have a triple foaf:person user{github acccount] and I can then use this to link the changeSet to your user. I think we willneed to pull the content of the Issue into the ontology as well so I'm coming up with something that will capture the issue text along with comments so that things are properly contained within the ontology. 

As a note I'm working on the GitHub integration and it will be triggered only by commits that contain additions (this should work for deprecation too) and with commit messages that contain some issue number so I can pull the Issue content from GitHub. I'll then find the Classes/Instances that were changed using the additions (easier said than done) and link the ChangeSet to the corresponding additions. This means if you link two issues they will both be linked. The only alternative is coming up with some other standard way of creating our commit messages so things are linked better.

**Comment by SusanBrown** [comment]
So -- decided not to link authors to github accounts by defaults

I think we also discussed but perhaps did not come to a conclusion about the idea that so as not to have the ontology get horribly cluttered with prose not to put in the issue comments but instead just the commit notes with links to the issues?

**Comment by joelacummings** [comment]
We did discuss that, I think it would be easiest for Rob and I to discuss this with you in person next week.

**Comment by joelacummings** [comment]
Here's how ChangeSets would be represented, we could either include the issue text in the long description or link to it. 

![changesets](https://user-images.githubusercontent.com/9123786/32851834-1fb9d706-ca04-11e7-91c8-5e43378e72e8.png)
