### ISSUE TITLE
Create event framework.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#186]
Create an event framework generic enough to be used for both personal and organizational events. Specific event classes include birth/death/life/afterlife events for individuals.

**Comment by rwarren2** [comment]
Add a mechanism to deal with an event's principal and attendance to institution.

**Comment by SusanBrown** [comment]
Can you elaborate on what you have in mind?


On Oct 25, 2017, at 12:44 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Add a mechanism to deal with an event's principal and attendance to institution.

**Comment by rwarren2** [comment]
Suggest `cwrc:EducationalAttendance` for SCHOOL/CHRONEVENT tags. 
Student's role would be `cwrc:student`
Suggest `cwrc:hostInstitution` as a role for the school/university itself.
@SusanBrown ?

**Comment by susanirenebrown** [comment]
Need clarification: 

Do you mean cwrc:EducationalAttendance as an event class? 

If so, I was thinking perhaps that we might have EducationEvent as a class for all events that occur within the Education tags. I think we said yesterday that we didn’t want to do a lot of subclassing of events, i.e. not have deep hierarchy, so this would mean we would have Events —> Life Events —> Education but not more specific than that, perhaps, so that we can class other events from this tagset?

What is the advantage of giving a school a role? Would hostInstitution over anything other than an educational institution? Something like educationalInstitution might be better because a) more specific and b) it’s possible that not all organizations are explicitly or solely universities or schools.

**Comment by rwarren2** [comment]
`cwrc:EducationEvent` as a subclass event done.

I suggest `cwrc:hostInstitution` as a role since it can cover joining a political organization or a publication house.
