### ISSUE TITLE
Review gender and sexual orientation terms against the diagram

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#187]
See what further definitions are needed for terms and predicates.

**Comment by jadepncr** [comment]
Things to correct:
- homosexualSexualIdentity, gaysSexualIdentity and queerSexualIdentity have to be changed since we treat them as instances of Sexuality 
- "gay" and "gay man" do not exist in the tagset, but we just have homosexual as an instance sexuality 
- "Queer" is not a Sexual Identity but an instance of Gender (genderqueer) 
- No space between "cis woman" and "trans woman" (same for the male equivalent) 
- Lesbian does not exist anymore but we have Lesbianism as sexuality 

Other things needs that may need to be added and/or changed:
- Remove SexualIdentity because it is not a label anymore 
- Gender instances are: cisgender, ciswoman, cisman, woman, man, transgender, transwoman, transman, androgynous and genderqueer
- Sexuality instances are: bisexuality, celibacy, frigidity, heterosexuality, homosexuality, lesbianism, libertinism and promiscuity 

Other remarks:
- There are two arrows "subClassOf" connecting woman and womanLabel 
- It is surely who is getting everything, but I do not understand in what way the instances of political affiliation are related to Sexuality. Iknow they are skos:related but I do not get why they appear in the gender diagram this way and these precise examples in particular (feminism, liberalism, Whig and gayRightsActivism) 
We could for example relate feminism to lesbianism and gayRightsActivism to genderqueer, homosexuality and bisexuality

**Comment by jadepncr** [comment]
Almost everything has been resolved, for the updated version of the diagram see v5 in the google folder. 

Issues that still need to be discussed: 
- do we use "-isms" terms ? (i.e. lesbian or lesbianism)
- queer as sexuality **and** gender ?
