### ISSUE TITLE
use eurovoc for Nationality, nationalHeritage, and geographicalHeritage throughout?

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#207]
Nationality and nationalHeritage need to point to a state/country not a spatial entity→ we thought we could use the eurovoc ontology -- does it actually define states or just places?

we need to investigate this before we come to a decision

prov: https://docs.google.com/document/d/1-Du1U7ScvSnu4bBzCfUnA0YE7EAwvZEtgG6mfZpMtJY/edit#

**Comment by SusanBrown** [comment]
Just investigated this. There are "political geography" entities, i.e. states, within EuroVoc, but no vocabulary for citizenship as distinct from this. So we could use these as related terms for citizenship but we're probably better to go with Wikipedia definitions, from what I can see, particularly since Eurovoc does not seem comprehensive in providing political geography entities. 

Therefore closing this issue for now. We may want to return to Eurovoc for cross-referencing but I don't think we need to unless we encounter an ontology for a related dataset that uses it, or unless we find that it is the best there is when we tackle referencing other ontologies more systematically.
