### ISSUE TITLE
Translate NaturalPerson and FictionalPerson definitions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#210]

**Comment by lemaka** [comment]
Hi Jade!

To this I'll add:

#TextLabels

#hasRaceColour

#hasLinguisticAbility

#hasNativeLinguisticAbility

#eurasianRace

#methodism

#occultism

I've looked -- because it strikes me as odd that these don't have definitions -- but I can't seem to find them in the spreadsheets.

Link to the ontology (http://sparql.cwrc.ca/testing/cwrc.html#eurasianRace), which you can use to search for these definitions that need translating.

reference issue here: https://github.com/cwrc/ontology/issues/212

**Comment by jadepncr** [comment]
Sorry it took so much time! There were many things I was reading for the first time so I had to think about it. I also pointed out some typos or weird things I found in the English versions. 


#ContexteReligieux 

Contexte Religieux est une sous-classe de contexte importante. Elle est associée à Religion, sous-classe de Forme Culturelle, et recoupe parfois avec d'autres Formes Culturelles.  Les annotations entrées en tant que Contexte Religieux fournissent des informations et des discussions sur la subjectivité d’une personne en lien avec sa religion. Contexte Religieux explore plus en détails les catégories granulaires d'une personne grâce aux propriétés a une religion ou a une affiliation religieuse (auto-déclarée).

#ContextePolitique 

Contexte Politique est une sous-classe de contexte importante. Elle est associée à Ethnicité, sous-classe de Forme Culturelle, et recoupe parfois avec d'autres Formes Culturelles.  Les annotations entrées en tant que Contexte Politique fournissent des informations et des discussions sur la subjectivité d’une personne en lien avec son activité politique. Contexte Politique explore plus en détails les catégories granulaires d'une personne grâce aux propriétés @@#aUneAppartenancePolitique@@ ou @@#aUneAppartenancePolitiqueAuto-Déclarée@@.

#EthnicityContext

> deprecated in the ontology for RaceEthnicityContext (at least I cannot find EthnicityContext alone in the current version) 

#AptitudeLinguistique
Décrit l'aptitude d'une personne pour parler, lire ou écrire une langue. 

#aUnGenre
Décrit le genre d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir genre. 

#aUneNationalité
Décrit la nationalité d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir nationalité. 

#aUneEthnicité
Décrit l'ethnicité d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir ethnicité. 

#aUneReligion
Décrit la religion d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir religion. 

#aUneClasseSociale
Décrit la classe sociale d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir classe sociale. 

#aUneSexualité
Décrit la sexualité d'une personne. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir sexualité. 

#aUnHéritageGéographique

Décrit l'héritage d'une personne en lien avec une situation géographique. Comme les toponomies et les frontières changent au cours du temps, une description de l'héritage géographique associée à une période historique donnée ne correspond pas toujours à celles des périodes antérieures ou postérieures, et ce même si elles possèdent le même nom. De même, le sentiment d'appartenance à un héritage géographique peut différer du sentiement d'appartenance à une entité politique du même nom. De même que pour les autres formes culturelles, une même personne peut cumuler plus d'une propriété ou description de ce type. Pour plus d'informations sur cette propriété, voir héritage géographique. 

**//!// "see geographic heritage" missing at the end of the English definition.** 

#héritageNationalAnglais

Indique qu'un sujet s'identifie à ou s'est vu assigner un héritage national anglais.

#héritageNationalGallois
Indique qu'un sujet s'identifie à ou s'est vu assigner un héritage national gallois.

#identitéNationaleJuive
Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale juive ou israélienne. 

#identitéNationaleAnglaise 
Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale anglaise. 

#jewishGeographicalHeritage

Indique qu'un sujet s'identifie ou s'est vu assigner une identité juive par rapport à un endroit, qui peut ou non être Israël. 

#ClasseMoyenneSupérieure

La classe moyenne supérieure est une classe sociale qui regroupe les individus de la classe moyenne dont les revenus sont les plus élevés (en France, supérieurs à 30 000 euros par an). En tant que membres de la classe moyenne, leurs revenus restent inférieurs à ceux de l'élite entrepreneuriale et des professions libérales. On y trouve surtout des cadres, parfois des artisans indépendants. La classe moyenne supérieure a tendance à se confondre avec la petite bourgeoisie, on y trouve par exemple un actionnariat développé ainsi qu'un niveau d'éducation élevé. Depuis les crises économiques des années 1970, la classe moyenne supérieure se distingue de plus en plus de la fausse jumelle, la classe moyenne inférieure ; la première étant caractérisée par son ascension sociale, l'autre par son déclassement.

prov:wasDerivedFrom:
dbpedia:Upper_middle_class

[Note: The DBpedia English definition sounds better and more nuanced than the French one. I can re-translate manually if it is important.]

#nationalismeAméricain 

Le nationalisme américain souligne la spécificité de la langue, de la culture et de l'histoire américaine et revendique la célébration de l'"américanité", pouvant inclure le nationalisme blanc et la lutte contre l'immigration. 

#Proaméricanisme

Le proaméricanisme ou posture "américanophile" défend la politique, les actions ou la culture des États-Unis d'Amérique. 

#étiquetteBlanc

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité de la blancheur de peau en tant que charactérique physique associée à diverses formes culturelles. Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "blanches" (par exemple nationalitéBlanche, raceCouleurBlanche). 

**//!!// Typo in the English version: "whiteRace" instead of "WhiteRaceColour"**
**Translation notes**: Longer version, "whiteness" becomes "la blancheur de peau en tant que charactérique physique" (for ideological reasons and linguistic accuracy). 

#étiquetteNoir

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité de la noirceur de peau en tant que charactérique physique associée à diverses formes culturelles. Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "noires" (par exemple ethnicitéNoire, raceCouleurNoire).

 **//!!// Same as above: two "black" labels send to blackRaceColour and blackEthnicity **

#étiquetteEurasie

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité du terme "eurasien·ne". Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "eurasiennes" (par exemple héritageGéographiqueEurasien, raceEurasienne).

#étiquetteAngleterre

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité du terme "anglais·e". Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "anglaises" (par exemple héritageGéographiqueAnglais, identitéNationaleAnglaise).

#étiquetteHomme

A subclass of textual label, this discursive label reflects the ambiguity of manhood, masculinity, or maleness as associated with different cultural forms. It provides a means of aggregating and searching multiple instances of "man" (e.g. man, cisman) cultural identities.

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité de la masculinité, ou de la virilité. Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "masculines" (par exemple homme, homme cis).

#étiquetteFemme

A subclass of textual label, this discursive label reflects the ambiguity of womanhood, femininity, or femaleness associated with different cultural forms. It provides a means of aggregating and searching multiple instances of "woman" (e.g. woman, transwoman/transfemale) cultural identities.

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité de la féminité. Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "féminines" (par exemple femme, femme trans).

#étiquetteJudaïsme 

Une sous-classe d'étiquettes textuelles, cette étiquette discursive reflète l'ambiguité de la juidaïcité. Elle permet de compiler et de rechercher les multiples instances d'identités culturelles "juives" (par exemple identitéNationaleJuive, raceCouleurJuive).

B)

#assignationRaceOuCouleur

Sous-propriété de propriété personnelle, décrit l'identité raciale d'une personne. Pour plus d'information sur cette propriété, voir race ou couleur. 

**Translation note:** "has" translated by "assignation" for ideological reason, since the word "race" does not have the same value in French (and more especially in France). Would need further discussion, but maybe not here!

#étiquettesTextuelles

Ensemble des étiquettes ambigues au sein du jeu d'étiquettes d'Orlando. 

#compétenceLinguistique

Capacité d'écrire ou de lire une langue.

#compétenceLinguistiqueNative

Capacité d'écrire ou de lire une langue. 

Should we precise "native language" to distinguish from the one above? 

#raceEurasienne

Un·e Eurasien·ne e est une personne d'ascendance mixte asiatique et européenne. Dans l'Inde britannique du XIXe siècle, les personnes d'ascendance eurasienne (plus tard anglo-indienne) étaient d'origine mixte portugaise, hollandaise, britannique, indienne ou, plus rarement, française, mais leur ascendance pouvait provenir d'autres régions de l'Asie du Sud, de l'Est ou du Sud-Est. Le terme est utilisé en anthropologie depuis les années 1960. Il peut également être étendu aux personnes possédant des origines d'Asie centrale.

> French DBpedia version not available, manually translated

#méthodisme

Issu d'un schisme avec l'Église anglicane, le méthodisme est un courant du protestantisme regroupant de nombreuses Églises d'orientations diverses, mais trouvant leur inspiration dans la prédication de John Wesley au XVIIIe siècle. Aujourd'hui, 80 millions de personnes se revendiquent méthodistes. Historiquement, le méthodisme est l'initiateur et le grand propagateur du Réveil qui va se propager à travers le monde, touchant des millions de personnes et revitalisant profondément le protestantisme. 

prov:wasDerivedFrom:
dbpedia:Methodism

#occultisme 

L’occultisme désigne l'ensemble des arts et sciences occultes (alchimie, astrologie, magie, divination, médecine occulte) touchant aux secrets de la nature, à ce qui est non visible. L'expression « sciences occultes » remonterait au titre d'un livre d'Eusèbe de Salverte, en 1829 (Des sciences occultes). Le mot « occultisme » en français ferait son apparition en 1842. Dès 1884 l'occultiste Joséphin Péladan entend par « occultisme » : « l'ensemble des sciences occultes ». En anglais, occultism date de 1881. Le néo-occultisme traite avec Papus des « facultés occultes de l'Homme » et des « forces invisibles de la Nature ». 

prov:wasDerivedFrom:
dbpedia:Occult

**Comment by alliyya** [comment]
@lemaka @SusanBrown I'm good to put in these definitions?

**Comment by SusanBrown** [comment]
Yes, go ahead. Pls put in our agenda anything that Jade has flagged for discussion.
