### ISSUE TITLE
cwrcFamily definition

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#226]
use: https://en.wikipedia.org/wiki/Family

_and append?_

Within the context of this ontology, cwrc:Family is not so much designed to address questions surrounding ‘blood ties,’ but offers instead a focus on the social (as opposed to biological) aspects of family relations.

**Comment by SusanBrown** [comment]
Looking at what we have in the ontology, we don't need to define Family so much as to group together the properties such as motherOf, FatherOf etc. Is that not right @alliyya @joelacummings

**Comment by lemaka** [comment]
I have the properties here:

auntOf
brotherOf
childOf
cousinOf
daughterOf
fatherOf
forebearOf
grandChildOf
grandDaughterOf
grandFatherOf
grandMotherOf
grandParentOf
grandSonOf
guardianOf
husbandOf
interpersonalRelationship
motherOf
nephewOf
nieceOf
parentOf
partnerOf
relativeOf
sibling
sisterOf
sonOf
stepBrotherOf
stepChildOf
stepDaughterOf
stepFatherOf
stepMotherOf
stepParentOf
stepSisterOf
stepSonOf
uncleOf
wifeOf

but I'm not sure what you mean by "group together"

**Comment by SusanBrown** [comment]
Ah, I guess the inverse properties are there. Scratch that.  

I mean that what is needed structurally for the ontology is an explanation of what these relationships are that groups them together. Not a definition of family plain and simple.

**Comment by SusanBrown** [comment]
I'm also not sure stylistically about using "of" when we use "has" for most other things. And the definitions of the relationships are not definitions.

Do you get what I'm saying about what needs defining? It's not family, but more something like Familial/Family Relationships.

**Comment by lemaka** [comment]
I think I catch your meaning now. 
I'll go away and try to craft something that links these terms.

**Comment by joelacummings** [comment]
For consistency I'd prefer using 'has' for a prefix.

**Comment by SusanBrown** [comment]
That’s my feeling too.

**Comment by lemaka** [comment]
Agreed.

Also, how's this @SusanBrown ?

Family relationships are social bonds assumed between a group of people affiliated by blood, marriage, or co-residence. For the purposes of this ontology, the focus is on the social aspects of familial relations as opposed to biological ones; for example, motherhood [link to the instance 'Mother'] as a role as opposed to a consanguineal assertion -- although both can be true. Family relationships are subproperties of interpersonal relationships. For more information, see "Family" [link to Dbpedia entry for 'family'?].

Not sure we need the last bit, but thought I'd add for good measure.

**Comment by SusanBrown** [comment]
Looks great.

**Comment by lemaka** [comment]
@alliyya could you please add the definition for Family Relationships (see two comments up)?

**Comment by alliyya** [comment]
@lemaka is this the definition for <owl:ObjectProperty rdf:ID="relativeOf"> or something else?

**Comment by SusanBrown** [comment]
Now @joelacummings how shall we approach the revision of the terms? I believe it will all work out if we replace "of" with "has" in all of them. 

Plus they all need revised definitions--what is there is insufficient, and it will be backwards once we change the predicates. I haven't looked at all the definitions for the terms in wikipedia but they seem adequate. Again they are for the relative not the relationship so we can't just adopt them but would need a definition.

HOWEVER, I still think we are rushing this. I am actually inclined NOT to go ahead even with this definition now @alliyya even though it is fine on its own, because there is work going on with other research groups involving biographical content that we should look at more carefully than we have in this area as well as others. I'm thinking particularly of the bio crm one: https://seco.cs.aalto.fi/projects/biographies/biocrm-2016-08-19.pdf. Also sharing an article about this on Slack.

**Comment by SusanBrown** [comment]
So in short, I think we should hold back. The terms were bunged into the ontology in the first place without enough research and discussion. I think it might be worth putting in the family relationships definition to flag our general approach, but not trying to really do a full job on the rest of family in haste.

What do people think?

**Comment by joelacummings** [comment]
I think we do want to standardize these terms with our standard relations names, but I'd also like to relate them to schema.org terms for person -- these definitions are quickly becoming the most prevalent if they are not already. Of note is that they are much more general but that makes the job easier :-)  This is related to #175 and I think we should tackle it now and not come back. 

Below I have come up with some base relations I think better reflect the way we currently do relations. One thing that I'm unsure of is if we need to be so specific -- will the data give us the precision to use these relations?

## Example Mapping

auntOf -> auntOf
brotherOf -> hasBrother
childOf -> hasChild
cousinOf -> hasCousin
daughterOf -> hasDaughter
fatherOf -> hasFather
forebearOf -> 
grandChildOf ->hasGrandChild
grandDaughterOf -> hasGrandDaughter
grandFatherOf -> hasGrandFather
grandMotherOf -> hasGrandMother
grandParentOf -> hasGrandparent
grandSonOf -> hasGrandSon
husbandOf -> hasHusband
motherOf -> hasMother
nephewOf -> hasNephew
nieceOf -> hasNiece
partnerOf -> hasPartner
relativeOf -> hasRelative
siblingOf -> hasSibling
sisterOf -> hasSister
sonOf -> hasSon
stepBrotherOf -> hasStepBrother
stepChildOf -> hasSetpChild
stepDaughterOf -> hasStepDaughter
stepFatherOf -> hasStepFather
stepMotherOf -> hasStepMother
stepParentOf -> hasStepParent
stepSisterOf -> hasStepSister
stepSonOf -> hasStepSon
uncleOf -> hasUncle
wifeOf -> hasWife

## Schema.Org Related Family Elements

Relation to Schema.org relations. Most of the Schema.org relations are are generic in that they are the inverse of themselves. They choose not to use 'has' or 'Of' to get around such issues. 

### **schema:sibling**

- stepSisterOf -> hasStepSister
- stepSonOf -> hasStepSon
- siblingOf -> hasSibling
- sisterOf -> hasSister
- brotherOf -> hasBrother


### **schema:parent -> schema:children**

- stepDaughterOf -> hasStepDaughter
- stepFatherOf -> hasStepFather
- stepMotherOf -> hasStepMother
- stepParentOf -> hasStepParent
- fatherOf -> hasFather
- motherOf -> hasMother

### **schema:spouse**

- wifeOf -> hasWife
- husbandOf -> hasHusband
- partnerOf -> hasPartner ?? -- Not sure if this quite fits


### **schema:relatedTo**

- nephewOf -> hasNephew
- nieceOf -> hasNiece
- relativeOf -> hasRelative
- cousinOf -> hasCousin
- auntOf -> auntOf
- uncleOf -> hasUncle

**Comment by SusanBrown** [comment]
I totally agree with the mappings to schema.org.

If we are going to deal with this "once and for all" there remains the question of definitions. The schema.org ones are pretty bald and won't work in many cases because they aren't exactly parallel. I was hoping that the bio ontologies that I pointed to might have helpful definitions and equivalents. The bio-crm one in particular might be useful but I can't easily find the ontology itself to look into definitions. 

I'd like someone to take this on and do some followup. Perhaps @joelacummings since you're running with this?

**Comment by joelacummings** [comment]
Done and added!
