### ISSUE TITLE
CWRC Ontology Review: to-fix 

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#237]
Unless otherwise flagged, this is a list for Abi to fix:

“This ontology adopts the broad FOAF definition of a foaf:person, which can be be applied to any entity considered to be a person, including non-humans. “ 
—> typo 
DONE

“Change Sets exist to track changes to instances, terms, and classes within the ontology, they are therefore used by both the authors of the ontology as well as users who are making additions or modifications. Changesets are instances that are linked either to or from a structure in the ontology. This is done through the object properties affected entity or through the skos:changeNote. A single changeset may apply to several entities therefore the affected entity relation may be applied 0 or more times. Changesets also track the user through the altered by relation and may link to any CWRC:Person. In addition dates and times are kept track of through time:inXSDDateTimeStamp using xsd:dateStamps to track the instant the change was applied to the ontology. This will allow changesets to be used as release by selecting them between a particular date to show major changes. Through provenance Change Sets may link to external resources allowing extended discussion to be kept out of the ontology. Shorter descriptions are included through the skos:changeNote relation as well as a title using a standard rdfs:label. Change Sets are to be used anytime an issue is completed by ontology developers or an instance is changed by a user. Automated mechanisms will be used to offset some of the work required.

Figure 3 - Change Set Example using both external descriptions and internal descriptions”
—> is it Change Sets or Changesets? @alliyya AGL: update -- I've decided it's two words.

“A Changeset represents changes or additions made to the ontology by ontology editors or through users where instances were affected. Change Sets will also be used to translate and contain Orlando recordInfo instances.”
—> here too
DONE

“A role of a Person or Actor in some Event, CreativeWork or Organisation”
—> missing a period
DONE

“An event whose principal is a person that is deceased. Could be used for a funeral, an influence over a living author or the estate of a deceased person.”
—> missing oxford comma
DONE

“They correspond broadly to the public high school in the United States and Canada and to the Gesamtschule in Germany.[citation needed]”
--> fix typo

cwrc:GeographicalHeritage
—> should be GoegraphicHeritage
DONE

cwrc:LanguageContext
—> this should be deprecated, @alliyya 
DONE

“A role of a Person or Actor in some Event, CreativeWork or Organisation”
—> missing period
DONE

“Social Class Context provides depth to more granular indications of Social class through the Social Class property.(Orlando, 2006)”
—> “Social” doesn’t need to be capitalized 
DONE

“Links a person to a Changeset entry”
—> missing a period and is Changeset spelled correctly?
DONE

“As with other cultural forms, an individual may have more than one property or descriptor of this type. For further information about this property, see .”
—> missing link after “see”…
DONE

“A subproperty of personal property, this describes a person's racial identity.—> this should have a “See RaceColour” link at the end
DONE

“sibling,” (properties) 
—> should this be “siblingOf” ? @alliyya 
DONE

“cwrc:EducationalAward_Prize”
—> feel as though this doesn’t need an underscore -- right, @alliyya ?
DONE

“cwrc:EducationalAward_Scholarship”
—> feel as though this doesn’t need an underscore
DONE

**general**:

should all definitions that cite DBpedia have

“Comment:
The description for this term is indebted to DBpedia.” @alliyya ?

answ: yes

**Comment by SusanBrown** [comment]
These all look good at a quick glance between flights. I have a similar list I will post as mentioned but it doesn’t overlap a ton so thanks for the careful reading Abi.  First one is fine as is though, I think.

Sent from my phone

On Feb 18, 2018, at 6:12 PM, lemaka <notifications@github.com<mailto:notifications@github.com>> wrote:


Unless otherwise flagged, this is a list for Abi to fix:

“What family members is a particular person recorded to have had, and how they were related?”
—> should be “were they” no?

“This ontology adopts the broad FOAF definition of a foaf:person, which can be be applied to any entity considered to be a person, including non-humans. “
—> typo

“Change Sets exist to track changes to instances, terms, and classes within the ontology, they are therefore used by both the authors of the ontology as well as users who are making additions or modifications. Changesets are instances that are linked either to or from a structure in the ontology. This is done through the object properties affected entity or through the skos:changeNote. A single changeset may apply to several entities therefore the affected entity relation may be applied 0 or more times. Changesets also track the user through the altered by relation and may link to any CWRC:Person. In addition dates and times are kept track of through time:inXSDDateTimeStamp using xsd:dateStamps to track the instant the change was applied to the ontology. This will allow changesets to be used as release by selecting them between a particular date to show major changes. Through provenance Change Sets may link to external resources allowing extended discussion to be kept out of the ontology. Shorter descriptions are included through the skos:changeNote relation as well as a title using a standard rdfs:label. Change Sets are to be used anytime an issue is completed by ontology developers or an instance is changed by a user. Automated mechanisms will be used to offset some of the work required.

Figure 3 - Change Set Example using both external descriptions and internal descriptions”
—> is it Change Sets or Changesets? @alliyya<https://github.com/alliyya>

“A Changeset represents changes or additions made to the ontology by ontology editors or through users where instances were affected. Change Sets will also be used to translate and contain Orlando recordInfo instances.”
—> here too

“A role of a Person or Actor in some Event, CreativeWork or Organisation”
—> missing a period

“An event whose principal is a person that is deceased. Could be used for a funeral, an influence over a living author or the estate of a deceased person.”
—> missing oxford comma

“They correspond broadly to the public high school in the United States and Canada and to the Gesamtschule in Germany.[citation needed]”
—> find citation

cwrc:GeographicalHeritage
—> should be GoegraphicHeritage

cwrc:LanguageContext
—> this should be deprecated, no?

“A role of a Person or Actor in some Event, CreativeWork or Organisation”
—> missing period

“Social Class Context provides depth to more granular indications of Social class through the Social Class property.(Orlando, 2006)”
—> “Social” doesn’t need to be capitalized

“Links a person to a Changeset entry”
—> missing a period and is Changeset spelled correctly?

“As with other cultural forms, an individual may have more than one property or descriptor of this type. For further information about this property, see .”
—> missing link after “see”…

“A subproperty of personal property, this describes a person's racial identity.—> this should have a “See RaceColour” link at the end

“sibling,” (properties)
—> should this be “siblingOf” ? @alliyya<https://github.com/alliyya>

“cwrc:EducationalAward_Prize”
—> feel as though this doesn’t need an underscore

“cwrc:EducationalAward_Scholarship”
—> feel as though this doesn’t need an underscore

doesn’t have a definition:

cwrc:EducationalAward

cwrc:EducationalOrganization

cwrc:Organization

cwrc:PrepSchool

general:

should all definitions that cite DBpedia have

“Comment:
The description for this term is indebted to DBpedia.” @alliyya<https://github.com/alliyya> ?

**Comment by alliyya** [comment]
also as instances they should be lowercase first letter

**Comment by alliyya** [comment]
Is LanguageContext being deprecated in favour of anything else? @lemaka

**Comment by alliyya** [comment]
> should all definitions that cite DBpedia have
> “Comment:
> The description for this term is indebted to DBpedia.” @alliyya ?

Yes and the corresponding provenance to the correct "http://dbpedia.org/resource/" page

**Comment by SusanBrown** [comment]
No but you could point to CulturalFormContext which would be the default in the absence of a more specific context.

**Comment by lemaka** [comment]
would you like for me to update the comments, then, @alliyya ? (asking so that we don't overlap)

**Comment by alliyya** [comment]
I have to step away for a bit so you can update the comments with no issue :)
