### ISSUE TITLE
genre relationships

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#241]
- [x] verse novel skos:broaderTerm poetry
- [x] sensation novel —> depending on the definition, either NT of novel only or change label to “sensation fiction” and make NT of fiction only.  The latter course is preferable.
- [x] biographicalDictionary NT of dictionary only (not also scholarship)
- [x] thesaurus NT of dictionary only (not also scholarship)
- [x] criminology NT of social science only (not also scholarship)
- [x] annotation skos:broaderTerm pretext
- [x] courtship fiction skos:broaderTerm fiction
- [x] devotional skos:broaderTerm religious
- [x] biblicalParaphrase skos:broaderTerm religious
- [x] nurseryRhyme skos:broaderTerm poetry
- [x] kitchenSinkDrama skos:broaderTerm drama
- [x] lettersFromTheDeadToTheLiving skos:broaderTerm epistolary
- [x] moralityOrMysteryPlay skos:broaderTerm drama
- [x] grammar skos:broaderTerm pedagogy
- [x] ghost story skos:broaderTerm fiction
- [x] bisexual fiction skos:broaderTerm fiction
- [x] utopia skos:broaderTerm fiction
- [x] dystopia skos:broaderTerm fiction

**Comment by alliyya** [comment]
@SusanBrown I can't find any mention of pretext within the genre ontology, is there another phrase you're thinking of or is this a new term that needs to be added?

**Comment by SusanBrown** [comment]
sorry: I think that was autocorrect: should be BT paratext

**Comment by jadepncr** [comment]
I add the review of the current genre diagram: http://sparql.cwrc.ca/testing/figures/genreTaxonomy-EN.svg
Everything remains open to discussion! 

**Relations to change or remove** 

- [ ] legal writing as NT of scholarship (because it is a form of technical writing) 
- [ ] panegyric as NT of drama 
- [ ] fabliau as NT of fable 
- [ ] young adult as NT of children literature (they are related, but I guess we cannot say young adult is a more specific form of children lit) 

**Possible relations to add** 
- [ ] comedy of manners NT drama
- [ ] novella NT fiction 
- [ ] black comedy NT comedy 
- [ ] bruletta NT comedy 
- [ ] biography NT scholarship 
- [ ] vignette NT fiction 
- [ ] elegy NT poetry 
- [ ] picaresque NT novel
- [ ] letters from the death to the living NT fiction
- [ ] parable NT fiction + didactic 
- [ ] magical realist NT fiction + novel 
- [ ] manual NT pedagogy 
- [ ] myth NT fiction
- [ ] answer NT epistolary, paratext, dialogue or debate  
- [ ] journalism NT political
- [ ] conduct literature NT didactic
- [ ] slave narrative NT historical 
- [ ] captivity narrative NT historical 
- [ ] regional NT fiction 
- [ ] erotica pornography NT fiction 
- [ ] coming out NT sexual awakening fiction + autobio 
- [ ] sexual awakening fiction NT autobio 
- [ ] fantasy NT fiction + science fiction 
- [ ] riddle NT didactic 
- [ ]  gardening NT manual 
- [ ] gothic NT fiction + novel
- [ ] fairy tale NT children literature 
- [ ] obituary NT poetry 
- [ ] fable NT didactic 
- [ ] epitaph 
- [ ] revue NT journalism 
- [ ] anthem NT political
- [ ] broadside NT political 
- [ ] detective NT mystery 
- [ ] nursery tale NT didactic 
- [ ] domestic NT novel, fiction
- [ ] notebook NT diary
- [ ] film TV script NT drama (?), adaptation 
- [ ] epithallama NT poetry 
- [ ] common place NT notebook 
- [ ] acrostic NT poetry 
- [ ] review NT scholarship, journalism 
- [ ] dialogue of the dead NT fiction
- [ ] dramatic monologue NT drama + monologue 
- [ ] monologue NT drama 
- [ ] radio drama NT adaptation
- [ ] adventure writing NT young adult, children, fiction
- [ ] periodical NT journalism, political 
- [ ] travel writing NT autobio 
- [ ] popular BT song, adventure writing, film TV script, comic book, erotica pornography, romance (?) 
- [ ] speech NT political 
- [ ] anthology NT scholarship 
- [ ] oriental NT historical
- [ ] industrial NT historical 
- [ ] government report NT political + legal writing 
- [ ] testimony NT autobiographical 
- [ ]  oratorio NT speech 
- [ ] nursery rhyme NT didactic

- [ ] multimedia sameAs (?) mixed media 

Missing English definitions: epitaph, regional 

This is all I have for now, I will do more "free floating" terms later.
