### ISSUE TITLE
can we add "identity"? eg. "race or colour identity" as opposed to "race or colour"

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#311]

**Comment by lemaka** [comment]
for reference: https://en.wikipedia.org/wiki/Hypatia_transracialism_controversy

**Comment by JasmineDW** [comment]
<b>Points of interest from "Not One" article:</b>

• "We understood identity as neither unitary nor immutable, and as much related to representational acts as to the lived experiences into which those representations blur" (14).
<i>^^ Considering CWRC's critical examination on the topic, including “identity” in the tagset acknowledges its significance/validity as well as unstable/social constructivist understandings of the term and its use.</i> 

• "in the spirit of Irigaray’s <b>simultaneous subversion of and participation in</b> the dominant representational framework, the project sought to use markup to label, while putting the act of labelling, as a means of fixing identity, under erasure" (14).
<i>^^ Methodology is actively anti-essentialist without dismissing identification terms that are significant to understanding subjective (and other) understandings of selfhood(...?). We will eventually be incorporating semiotic theories in relation to labels (e.g. Derrida's slipperiness of signifiers, and meaning understood relationally through difference/différance) into Ontology preamble and/or future publications.</i>

• "[The self-definition] approach to encoding author identities, as it turned out, allows for the emergence of non-narrative, collaboratively produced representations of identity as shifting, intersectional, and always already relational" (16).
<i>^^ In attaching "gender" or "race" to "identity" (becoming "Race Identity" for example), the preceding terms become adjectives and thusly instances of identity as a thing rather than things unto themselves.</i> 

• "Orlando’s contributors have described and marked up the intersectional identities of more than 1300 writers.  They can be accessed through searches in terms of their identities and those identities can also be represented as multiple, shifting, complex" (18-19).
<i>^^ Including the term "identity" could help make this multiplicity/slipperiness more explicit.</i>

**Comment by lemaka** [comment]
@antimony27 , could you contact Connie and review the above

**Comment by alliyya** [comment]
Note:
Changes will also have to reflect onto the definitions and possible uris
Some Classes to look at:
- Nationality
- Sexuality
- Gender
- Ethnicity
- RaceColour
Possibly others (please expand list as necessary)

**Comment by lemaka** [comment]
**Decision**: we are going w "identity" for the predicates (eg. hasGenderIdentity), but NOT for the instances (eg. we would only say "Scottish"), NOR Contexts (eg. hasGenderContext).

**Comment by alliyya** [comment]
These are the changed labels
```
#hasGender => has gender identity
#hasGenderSelfReported => has gender identity (self-reported)
#hasGenderReported => has gender identity (reported)
      
#hasGeographicHeritage => has geographic heritage
#hasGeographicHeritageSelfReported => has geographic heritage (self-reported)
#hasGeographicHeritageReported => has geographic heritage (reported)
      
#hasNationality => has national identity
#hasNationalitySelfReported => has national identity (self-reported)
#hasNationalityReported => has national identity (reported)
      
#hasRaceColour => has race or colour identity
#hasRaceColourSelfReported => has race or colour identity (self-reported)
#hasRaceColourReported => has race or colour identity (reported)
      
#hasEthnicity => has ethnic identity
#hasEthnicitySelfReported => has ethnic identity (self-reported)
#hasEthnicityReported => has ethnic identity (reported)
      
#hasSexuality => has sexual identity
#hasSexualitySelfReported => has sexual identity (self-reported)
#hasSexualityReported => has sexual identity (reported)
  ```

**Comment by alliyya** [comment]
@lemaka 
can you confirm that identity is not to be attached to the following properties and respective subproperties

- hasLinguisticAbility
- hasNationalHeritage
- hasNativeLinguisticAbility
- hasPoliticalAffiliation
- hasReligion
- hasSocialClass

**Comment by alliyya** [comment]
French labels and definitions will need to also modified to reflect these changes

**Comment by SusanBrown** [comment]
label for hasSocialClass to become has Class Identity
