### ISSUE TITLE
Missing Race or Colour instances

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#319]
- [x] add "creole" for raceOrColour?
- [x] revisit the question of strings w respect to "yellow"

**pasted decision from below:**

Joel decided: keep "yellow" and similar occurrences as strings (need to make data properties for these)

Susan decided: we will create a definition for "creole" for raceOrColour

**from meeting on May 8th:**

For CulturalForms use SKOS: alt and possibly use WordNet for alternative terms, linking strings to terms (eg. cwrc:Jewish would link to all its string variants -- currently hidden in the CSS, but in the ontology)

**Comment by alliyya** [comment]
Only Spreadsheet I can see referencing _Yellow_ and _creole_:
https://docs.google.com/spreadsheets/d/1c2tSK7oqwHeSc1YFLjnEEgaGzVk8DMn1Y3O10I8PD08/edit#gid=1712277612

#59 issue with freeform and reg race instances

**Comment by lemaka** [comment]
Thanks for the above! Should have been clearer --it's not that they were "missed" but that Susan wants to revisit the question of whether they should be created and added.

**Comment by lemaka** [comment]
Joel decided: keep "yellow" and similar occurrences as a strings
Susan decided: we will create a definition for "creole" for raceOrColour

**Comment by lemaka** [comment]
**cwrc:creole**

@SusanBrown, something like?: 

Describes a person often born in a European (often British) colony, of "mixed race" parentage, usually the child of "White" and so-called "non-White" ancestry. The term originally designated "parts of the population made up of Caribbean descendants of colonists, born and brought up in the New World. In the context of postcolonial studies, the term 'creolization' is conceived as 'the process of intermixing and cultural change that produces a Creole society,' especially in the Caribbean (Ashcrofts, Griffiths, and Tiffin 1998, 58)" (Hawley et al., Encyclopedia of Post Colonial Studies 116).

**Comment by SusanBrown** [comment]
@alliyya we can go ahead with this definition, which is good. I notice that we have creole as an altLabel on white: [skos:altLabel: creole (typically caucasian (european settler descendants) ]

Is this a problem or will it be displaced by the definition of creole?

**Comment by alliyya** [comment]
Alt labels in general need to be revised wrt to the scrapes I've done, I added a few but I'm holding off on fully reviewing them until all missing instances for cultural forms are within the ontology, will create creole instance of racecolour now

**Comment by alliyya** [comment]
@GurjapSingh If you could add the sources from Abi's definition to the cwrc bibliography and provide the links so I can add them so the def'n is properly linked, that would be great!

**Comment by GurjapSingh** [comment]
- Hawley, John Charles, ed. Encyclopedia of postcolonial studies. Greenwood Publishing Group, 2001.(https://beta.cwrc.ca/islandora/object/cwrc%3Aaa8dae29-558b-4bda-9859-9ed43faede36#)

- Ashcroft, B., et al. Key Concepts In Post-Colonial Studies. no date. Literary Criticism, 1998. (https://beta.cwrc.ca/islandora/object/cwrc%3Aa647a149-3420-4a0d-8462-03900131060e)

Are these okay?

**Comment by alliyya** [comment]
Missing RaceColour terms:

- Native American
- Afro-Caribbean 

These were in the spreadsheet but seemed to get misplaced going through the history.
Unless these were deleted for a reason, there's still 4 instances of Native american in Orlando and 1 of 
Afro-Caribbean

Proposed Definitions & Labels:
URI: afro-CaribbeanRaceColour
Label: Afro-Caribbean
Definition: "African-Caribbeans are Caribbean people who trace their heritage to Africa in the period since Christopher Columbus's arrival in the region in 1492. Other names for the group include African-Caribbean (especially in the UK branch of the diaspora), Afro-Antillean or Afro-West Indian. Between the 16th and 19th centuries, European-led triangular trade brought African people to work as slaves in the Caribbean on various plantations. Many Afro-Caribbeans also have non-African ancestry, such as European, South Asian, East Asian, Middle Eastern and Native American, as there has been intermarriage over the centuries." `<![CDATA[<a href="#cwrc:c5e7bace-95bb-4820-bd7d-6bb97c1badc5">(DBpedia, 2018)</a>]]>`

URI: indigenousPeoplesOfAmericasRaceColour
Label: Indigenous (of the Americas)
AltLabel: Native American
Definition: Same as one from http://sparql.cwrc.ca/testing/cwrc.html#indigenousPeoplesOfAmericasEthnicity 

What do you think? @SusanBrown

**Comment by SusanBrown** [comment]
agreed
