### ISSUE TITLE
Forebear graffle: final review

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#339]
Still pending identity decision, but pls review and will move to approved regardless.

**Comment by alliyya** [comment]
@SusanBrown is it possible to make the boxes wider to fit the uris all on one line, otherwise it looks a bit off being randomly broken apart.

cwrc:Person is not a term currently in the ontology as we have natural person (http://sparql.cwrc.ca/testing/cwrc#Natural Person) and fictional person (http://sparql.cwrc.ca/testing/cwrc#Fictional Person)

I've also added a comment on the png in the folder

**Comment by SusanBrown** [comment]
I was afraid you would say that. There isn’t space: the whole thing will have to be reshaped. But I take the point. Sigh.


On Apr 22, 2018, at 1:53 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> is it possible to make the boxes wider to fit the uris all on one line, otherwise it looks a bit off being randomly broken apart.

cwrc:Person is not a term currently in the ontology as we have natural person (http://sparql.cwrc.ca/testing/cwrc#Natural Person) and fictional person (http://sparql.cwrc.ca/testing/cwrc#Fictional Person)

I've also added a comment on the png in the folder

**Comment by SusanBrown** [comment]
@alliyya  Revised version here: https://drive.google.com/open?id=11AX2KHrmuM-jRv1-sYsCusgghOyIFqBj
Couldn't see comment on the png so may have missed some things.

**Comment by alliyya** [comment]
Other than Identity issue raised in #311, approved

**Comment by SusanBrown** [comment]
Needs updating to reflect identity decision

**Comment by GurjapSingh** [comment]
this has been updated to reflect identity changes
