### ISSUE TITLE
Cultural Formation classes - check

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#37]
Queries: Do we have sexIdentity in addition to SexualIdentity? The ontology says we do. Also CisGendered, Androgynous, TransGender and GenderQueer are classes which I don't think is right. We seem to be lacking RaceColourContext.

**Comment by rwarren2** [comment]
CisGendered is a class because 'heterosexual male' and 'heterosexual female' would be instances of such and SexualIdentity. SexIdentity was meant to reflect whatever came in from the census which is what Orlando records in the XML. 

I have to look at this a little bit more, not all of the structure and terms are in here.

**Comment by rwarren2** [comment]
About RaceColourContext, we had decided in the meeting that there would be a RaceEthnicityContext but no RaceColourContext while there was a RaceColour as a Cultural Formation.

**Comment by rwarren2** [comment]
I'm updated figure 2 into the DH submission.

**Comment by SusanBrown** [comment]
So RaceEthnicityContext serves both RaceEthnicity and RaceColour

And CisGendered would be a subclass of Gender

I don't follow what you mean about SexualIdentity and the Census wrt Orlando data.
