### ISSUE TITLE
Multiple instances of same triple

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#427]
Need to discuss what to do when we have multiple instances of the same triple. Weighting might be a good solution.

**Comment by alliyya** [comment]
Capturing thoughts from meeting

- This won’t occur with the nature of how triples are stored/serialized
- There can only be one
- However because of this we won’t be able to capture certain counts like how many times a writer visited a specific location. Is this an issue? YES!
- They will be recorded in the contexts, perhaps a shacl rule to handle recurring triples across multiple contexts

@joelacummings 
Since a "triple" will be connected through multiple contexts; is it feasible to make a SHACL rule that counts the number of times the same triple occurs within multiple contexts?

**Comment by joelacummings** [comment]
Should be able to use SHACL or SPARQL to solve these issues.
