### ISSUE TITLE
define and add hasMedium / mediumOf to Genre Ontology

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#536]
We currently have `genre:Genre`, `genre:Form` and `genre:Medium` as top-level concepts/classes in the Genre ontology, and have the associated properties of: `genreformOf`, `genre:genreOf`, `genre:hasForm`, `genre:hasGenre`, but no existing predicate for mediums. 

If this is not intentional then we should likely add `hasMedium` / `mediumOf` to the genre ontology.

**Comment by alliyya** [comment]
Extraction to be updated to make use of `hasMedium` similar to hasForm/hasGenre

**Comment by JasmineDW** [comment]
@SusanBrown please review before implementation:

**hasMedium:**
Describes the material used to produce a cultural work and/or the governing substance that defines a particular object, digital or otherwise. Objects may have multiple mediums.

**mediumOf:**
This is the inverse of has medium, whose definition is as follows:
Describes the material used to produce a cultural work and/or the governing substance that defines a particular object, digital or otherwise. Objects may have multiple mediums.

**Note:** Definition of hasForm/formOf must be modified to remove mention of "medium". Definition is currently:
"Describes the form of a cultural artifact, including material form or medium; type of publication such as serialization; or organization of content such as record. Objects often have multiple forms."

**Comment by SusanBrown** [comment]
Good to go!

**Comment by alliyya** [comment]
@alliyya check if this change has been reflected in the extracted data.

**Comment by alliyya** [comment]
@JasmineDW Can you add this term to the ontology? It's already being extracted.
