### ISSUE TITLE
Ordering of given names in Orlando Markup

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#57]
In the following Orlando markup:

<BIRTHNAME REG="Wemyss, Margaret"> <GIVEN>Jean</GIVEN> <GIVEN>Margaret</GIVEN> <SURNAME REG="Laurence, Margaret">Wemyss</SURNAME> </BIRTHNAME>

Is there any underlying order to the Jean and Margaret given names? The schema is quiet about this but the ordering of given names in the REG attribute seems to indicate some standardization.

**Comment by SusanBrown** [comment]
I think they would be listed in the order in which they were given that is first given name first and so on.

Sent from my iPhone

On May 24, 2017, at 11:57 AM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


In the following Orlando markup:

Jean Margaret Wemyss

Is there any underlying order to the Jean and Margaret given names? The schema is quiet about this but the ordering of given names in the REG attribute seems to indicate some standardization.

**Comment by SusanBrown** [comment]
There are other rules for the standardization of names, and they are documented in the Orlando schema under the "NAME" tag:

name

Definition

The name element is used to track people across our history of women's writing. The contents of the name element will not only be used to index people but to draw attention to the relationships among people, based on the appearance of names in bio-critical documents, in chronology events, and according to proximity searches across the project.

Placement

Biography

Events

Writing

Name should contain only the name of a person and should exclude any extraneous information or punctuation.

Relationships

Name is a global element that can be inserted wherever it is valid to type (i.e. in paragraphs, chronProse, and dataItems). It is modified by the optional standard attribute.

Examples

<name>Virginia Woolf</>
<name>Sarah Ferguson</>
<name>Sarah Flower Adams</>
<name STANDARD="Louis XVI,, King of France">Louis XVI</>
<name STANDARD="Brougham, Henry Peter,,, Baron">Lord Brougham</>
Practice Issues

In order to systematize names across the project, it is important that a person's name always be expressed in a standard fashion. To find a person's standard name please consult the following sources (listed in order of authority). If you cannot find the name in one of these sources or if there is some conflict surrounding the standard name, please contact the appropriate volume author.

i. Orlando document archive catalog
ii. FC: for women writers: (Standard names are written in bold in the FC)
iii. Drabble: for male writers
iv. DNB: for Brit non-writers (except for those with peerage title)
v. BLC online
vi. Everyman's Encyc/Encl Brit
vii. LC authority files (author name in the Gate)
When and how to standardize a name

Most names that you enter will not require any use of the standard attribute: names entered in standard format (Lastname, Firstname); names entered in standard reading order provided the ordering of the name is simple first name (can be compound) followed by simple last name (cannot be compound). All other names should be regularized using the tag's standard attribute.

The use of commas in standard attributes must be precise in order to accommodate complex names. Please use commas carefully and accordingly:

a single comma would place everything that follows it before everything that precedes it in order to establish natural reading order: Caird, Mona = Mona Caird. Grove, Sir George = Sir George Grove
a double comma would place everything that follows it at the end of the name in natural reading order and would add a comma to the display: Marie-Antoinette,, Queen of France = Marie-Antoinette, Queen of France
a triple comma should appear in combination with a single comma and would defer to the ordering principle of the single comma but would add a comma as punctuation: Carlisle, George William Frederick Howard,,, Seventh Earl of = George William Frederick Howard, Seventh Earl of Carlisle
Difficult names and how to handle them

If the name begins with d', de, von, van and other standard prefixes, and if the person is not indexed in any of the approved list of sources named above, index according to the first capital letter of the surname whether or not it is part of a prefix:

Aelders, Etta Palm d'
D'Israeli, Isaac
Kotezebue, August von
La Tourette, Aileen
Titles of French people such as comte and marquis should be in lower case:

Artois, comte d'
Condé, prince de
Hyphenate all double-barreled French names:

Marie-Antoinette,, Queen of France
Voltaire, Jean-Francois-Marie Arouet de
Due to a software problem, foreign names requiring accents cannot, at this point, acquire accents in the standard attribute. If a name has an accent (such as Madeleine de Scudéry) you will need to put an anglicized version of the name in the standard attribute and then indicate the properly standardized version in a research note placed inside the name tag.

All references to maiden names, previous names, or future names should not be part of the standard name: such names may appear in the text of the name tag in brackets but should not be part of the standard name unless they are considered a part of the standard name according to the authoritative sources listed above:

Susannah Maria (Arne) Cibber
Olympe de Gouze (formerly Marie Gouze)
Names that have initials should be represented with periods and spaces as follows: in text: T. S. Eliot; in standard attribute: Eliot, T. S.

Where non-peerage titles are part of standard name according to sources above, use abbreviations: Mr, Mrs, Mme, M., Dr, Rev. Note that a period follows the abbreviation only when the abbreviation ends in a letter different from the letter that the word itself ends in.

Monarchs in standard attribute: please note roman numerals and spelling of Tsar.

Of England:

Henry I, King
Henry IV, King
Richard II, King
Victoria, Queen
Elizabeth II, Queen
Of other countries:
Alexander II,, Tsar of Russia
Catherine the Great,, Queen of Russia
Louis IX,, King of France
Napoleon II,, Emperor of France
The standard name of anyone who has been a monarch should be their monarchic name. Therefore, fill in the standard attribute for Prince of Wales and the like to the proper monarchic name. The only exception to this rule is Napoleon Bonaparte whose standard name is not his monarchic name.
Popes and other religious titles in standard attribute: please note roman numerals:

John XIII, Pope
Pius IV, Pope
Mary Agnes, Sister
Hanley, Sister
Peerage:all people with peerage titles should be indexed by title (not name) in the standard attribute (the DNB does this the opposite way, so beware). If you have both name and title, use both but remember to index according to title. Occasionally you will find a person who has a peerage title that is not part of a standard name (e.g. Horace Walpole). Defer to the list of sources above in these matters to determine standard name. Spell out all numbers that have to do with peerage titles. Please refer to comma ordering principles listed above.

Montagu, Lady Mary Wortley
Stanley, Henrietta Maria,,, Lady
North, Lord
Grove, Sir George
Northbrook, Thomas George Baring,,, Lord
Cranworth, Robert Monsey Rolfe,,, Baron
Condorcet, Marie-Jean-Antoine-Nicolas Caritat,,, marquis de
Notes: "Lady" with Christian name means she received her title from her father; "Lady" with surname means she got her title by marriage. "Marquess" is the British spelling for "Marquis"; use for all British people with this title. "Earl", "Baron", and "Marquess" are more precise titles than the more general "Lord" which covers the bunch; if you have the more precise title, use it.
