### ISSUE TITLE
is NationalHeritageContext a context that should exist?

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#64]

**Comment by SusanBrown** [comment]
Can we have both NationalHeritage and Nationality covered by NationalityContext? I think that would be best.

**Comment by rwarren2** [comment]
After discussion with @antimony27 and @SusanBrown, we will split NationalHeritageContext and NationalityContext as it is unclear what Orlando's granularity and use of tags is in practice. Also see Issue #63.

**Comment by lemaka** [comment]
this needs to be captured in the ontology, then (adding this to my to-dos)

**Comment by SusanBrown** [comment]
Sorry to muddy the waters but I don’t recall this discussion and right now feel happy with the idea of just a single NationalityContext rather than breaking them out. Simpler might be better?


On Jul 23, 2017, at 11:33 AM, lemaka <notifications@github.com<mailto:notifications@github.com>> wrote:


this needs to be captured in the ontology, then (adding this to my to-dos)

**Comment by rwarren2** [comment]
What happens when both Orlando tags exist, should the data be concatenated into the same instance?

**Comment by susanirenebrown** [comment]
If they share the same context string, then both triples should be linked to that context, if that is what you mean. There is only the NatioanalityIssue tag in the tagset so NationalHeritageContext would occur inside it if at all.

**Comment by rwarren2** [comment]
NationalityContext to be used in a all cases.
