### ISSUE TITLE
Create textuality property definitions:

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#82]
cwrc:alludesExplicitlyTo
   cwrc:respondsTo
 cwrc:alludesExplicitlyTo <http://www.cwrc.ca/cwrcdata/ElizabethI> ;
   cwrc:relatesByMaterialFeaturesTo   cwrc:contestsGenre cwrc:genreBiography ;
   cwrc:contestsGenre 
  cwrc:relatesByCirculationTo 
  cwrc:relatesByManuscriptTo 
   cwrc:relatesByArchiveTo 
   cwrc:hasSetting 
 cwrc:relatesEroticallyTo
   cwrc:influences
cwrc:relatesPoliticallyTo 
   cwrc:relatesBySisterHoodTo 
   cwrc:relatesTextuallyTo 
   cwrc:relatesByReceptionTo
   cwrc:relatesByEducationTo 
 cwrc:hasReceptionRelationTo
 cwrc:adapts

**Comment by JasmineDW** [comment]
Do these terms still need to be added?
- cwrc:relatesByMaterialFeaturesTo
- cwrc:contestsGenre
- cwrc:relatesTextuallyTo
- cwrc:hasSetting
- cwrc:relatesByManuscriptTo
- cwrc:relatesByArchiveTo

Replaced by Cultural forms?
- cwrc:relatesByEducationTo
- cwrc:relatesBySisterHoodTo
- cwrc:relatesPoliticallyTo
- cwrc:relatesEroticallyTo

**Comment by alliyya** [comment]
I think the [spreadsheet](https://docs.google.com/spreadsheets/d/19h61m3maWIG50eR3dZzWlRx9TnGEGye4ZWKwu9bC9kc/edit#gid=2071969509) would be a better ground truth of textuality properties to be created rather than this issue. There's just not a whole lot of context with these terms as is.

Maybe best steps is to cross-check with spreadsheet and data to see if any of these properties should be created in addition to the ones in the spreadsheet.
