### ISSUE TITLE
Html rendering: not all clicks lead to definitions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#87]
So when I click on a genre name in the list of instances:
![image](https://user-images.githubusercontent.com/545952/28229004-f33bc876-68ae-11e7-887c-6da4ed2e768a.png)
the definition is not visible:
![image](https://user-images.githubusercontent.com/545952/28229017-01df3d68-68af-11e7-8af4-c2fcd65ad433.png)
but if I click on the URI, it becomes visible:
![image](https://user-images.githubusercontent.com/545952/28229025-0e35c0be-68af-11e7-9c11-f23605ab2b57.png)
But then the citation of the source has disappeared.

We want both the definition and the citation of the source to be visible!

**Comment by alliyya** [comment]
See issue #88, two different webpages, link [http://sparql.cwrc.ca/testing/cwrc.html#genreEpitaph](http://sparql.cwrc.ca/testing/cwrc.html#genreEpitaph) and uri takes you to [http://sparql.cwrc.ca/ontology/cwrc.html#genreEpitaph](http://sparql.cwrc.ca/ontology/cwrc.html#genreEpitaph) which has the proper definition, will be fixed in next deploy with updated document generator

**Comment by SusanBrown** [comment]
great!



On Jul 14, 2017, at 7:09 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


See issue #88<https://github.com/cwrc/ontology/issues/88>, two different webpages, link http://sparql.cwrc.ca/testing/cwrc.html#genreEpitaph and uri takes you to http://sparql.cwrc.ca/ontology/cwrc.html#genreEpitaph which has the proper definition, will be fixed in next deploy with updated document generator

**Comment by rwarren2** [comment]
Closing ticket.
