### ISSUE TITLE
Predicate for non- terms in Political Affiliation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#93]
This is related to https://github.com/cwrc/ontology/issues/84

Rather than creating instances for things like non-pacifism, I think it would be better to refer to pacifism, which is more of a real PA than non-pacifism.

We need a predicate, folks! 

If the predicate is (as I'm currently thinking) Affiliates Politically With, then here are some possibilities: 

Uninvolved Politically With
Distanced Politically From
Unaffiliated Politically With

Thoughts? Better ideas?  @antimony27 @lemaka @jadepncr

**Comment by rwarren2** [comment]
I get to recycle my old Ontology paper yet again in this discussion!
http://rdf.muninn-project.org/ontologies/appearances.html#term_hasRomanticAversion
http://rdf.muninn-project.org/ontologies/appearances.html#hasRomanticPreference

One of the basis for the above was the notion of *preference* vs. *requirement* or as a direct examples: not wanting to eat nuts because one has a deadly allergy vs. not wanting to eat nuts because one dislikes them. There may be room for a 'weaker' version of a relationship through sub-properties may not be the way to go since a requirement implying a preference is just asking for trouble.

This does bring up the question of what **UninvolvedPoliticallyWith** really means: is this a direct choice not to participate or an ignorance of the organization which is likely to occur for a very large number of people?

Similarly, for **DistancedPoliticallyFrom** does this mean that the person deliberately did something to distance themselves from it and if so, should we create an event instead?

**Comment by SusanBrown** [comment]
We are not extracting these until after DH2017, when we will revisit this issue.

**Comment by alliyya** [comment]
ContraryTo property has been created
